version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  post_build:
    commands:
      - mvn package
      

artifacts:
  files:
    - target/bt.war
    
  base-directory: 'target/bt'
